# Exported from Render on 2025-07-10T06:45:52Z
services:
- type: web
  name: orbify_backend
  runtime: node
  repo: https://github.com/addityaasharma/orbify_backend
  plan: free
  envVars:
  - key: REDIS_URL
    sync: false
  - key: EMAIL_PASSWORD
    sync: false
  - key: EMAIL_USER
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: MONGO_URI
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node server.js
  autoDeployTrigger: commit
version: "1"
